### ISSUE TITLE
Phinx recipes

### ISSUE THREAD

**Issue by security-database** [deployphp/recipes#74]
Hello

It seem that phinx recipe is not working anymore with deployer 4.0.

**Comment by elfet** [comment]
Can you careate pr to fix it?

**Comment by security-database** [comment]
I think it's a PHP7 incompatibility and a miss of namespace Deployer;

Afetr adding namespace Deployer on the top,
thow me an error when i deployer phinx:migrate

Seem that PHP7 don't like, for exemple:
`$conf = get('phinx_get_allowed_config')($ALLOWED_OPTIONS);
`

```
Executing task phinx:migrate
PHP Warning:  Missing argument 1 for Deployer\{closure}() in /project-root/vendor/deployer/recipes/phinx.php on line 94
PHP Stack trace:
PHP   1. {main}() php/bin/deployer.phar:0
PHP   2. require() php/bin/deployer.phar:4
PHP   3. Deployer\Deployer->run() phar://php/bin/deployer.phar/bin/dep:110
PHP   4. Symfony\Component\Console\Application->run() /project-root/vendor/deployer/deployer/src/Deployer.php:186
PHP   5. Symfony\Component\Console\Application->doRun() /project-root/vendor/symfony/console/Application.php:122
PHP   6. Symfony\Component\Console\Application->doRunCommand() /project-root/vendor/symfony/console/Application.php:191
PHP   7. Symfony\Component\Console\Command\Command->run() /project-root/vendor/symfony/console/Application.php:829
PHP   8. Deployer\Console\TaskCommand->execute() /project-root/vendor/symfony/console/Command/Command.php:255
PHP   9. Deployer\Executor\SeriesExecutor->run() /project-root/vendor/deployer/deployer/src/Console/TaskCommand.php:79
PHP  10. Deployer\Task\Task->run() /project-root/vendor/deployer/deployer/src/Executor/SeriesExecutor.php:40
PHP  11. call_user_func:{/project-root/vendor/deployer/deployer/src/Task/Task.php:91}() /project-root/vendor/deployer/deployer/src/Task/Task.php:91
PHP  12. Deployer\{closure}() /project-root/vendor/deployer/deployer/src/Task/Task.php:91
PHP  13. Deployer\get() /project-root/vendor/deployer/recipes/phinx.php:120
PHP  14. Deployer\Server\Environment->get() /project-root/vendor/deployer/deployer/src/functions.php:512
PHP  15. call_user_func:{/project-root/vendor/deployer/deployer/src/Server/Environment.php:126}() /project-root/vendor/deployer/deployer/src/Server/Environment.php:126
PHP  16. Deployer\{closure}() /project-root/vendor/deployer/deployer/src/Server/Environment.php:126

Warning: Missing argument 1 for Deployer\{closure}() in /project-root/vendor/deployer/recipes/phinx.php on line 94

Call Stack:
    0.0042     357872   1. {main}() php/bin/deployer.phar:0
    0.0466     708864   2. require('phar://php/bin/deployer.phar/bin/dep') php/bin/deployer.phar:4
    0.1532    4198624   3. Deployer\Deployer->run() phar://php/bin/deployer.phar/bin/dep:110
    0.1684    4333416   4. Symfony\Component\Console\Application->run() /project-root/vendor/deployer/deployer/src/Deployer.php:186
    0.1818    4334248   5. Symfony\Component\Console\Application->doRun() /project-root/vendor/symfony/console/Application.php:122
    0.1829    4334248   6. Symfony\Component\Console\Application->doRunCommand() /project-root/vendor/symfony/console/Application.php:191
    0.1830    4334248   7. Symfony\Component\Console\Command\Command->run() /project-root/vendor/symfony/console/Application.php:829
    0.1843    4336824   8. Deployer\Console\TaskCommand->execute() /project-root/vendor/symfony/console/Command/Command.php:255
    0.1879    4375224   9. Deployer\Executor\SeriesExecutor->run() /project-root/vendor/deployer/deployer/src/Console/TaskCommand.php:79
    0.1904    4409792  10. Deployer\Task\Task->run() /project-root/vendor/deployer/deployer/src/Executor/SeriesExecutor.php:40
    0.1905    4410112  11. call_user_func:{/project-root/vendor/deployer/deployer/src/Task/Task.php:91}() /project-root/vendor/deployer/deployer/src/Task/Task.php:91
    0.1906    4410112  12. Deployer\{closure}() /project-root/vendor/deployer/deployer/src/Task/Task.php:91
    0.1906    4410488  13. Deployer\get() /project-root/vendor/deployer/recipes/phinx.php:120
    0.1907    4410488  14. Deployer\Server\Environment->get() /project-root/vendor/deployer/deployer/src/functions.php:512
    0.1909    4410488  15. call_user_func:{/project-root/vendor/deployer/deployer/src/Server/Environment.php:126}() /project-root/vendor/deployer/deployer/src/Server/Environment.php:126
    0.1909    4410488  16. Deployer\{closure}() /project-root/vendor/deployer/deployer/src/Server/Environment.php:126


Variables in local scope (#16):
  $allowedOptions = *uninitialized*
  $e = *uninitialized*
  $key = *uninitialized*
  $opts = *uninitialized*
  $val = *uninitialized*

PHP Fatal error:  Uncaught Error: Function name must be a string in /project-root/vendor/deployer/recipes/phinx.php:120
Stack trace:
#0 [internal function]: Deployer\{closure}()
#1 /project-root/vendor/deployer/deployer/src/Task/Task.php(91): call_user_func(Object(Closure))
#2 /project-root/vendor/deployer/deployer/src/Executor/SeriesExecutor.php(40): Deployer\Task\Task->run(Object(Deployer\Task\Context))
#3 /project-root/vendor/deployer/deployer/src/Console/TaskCommand.php(79): Deployer\Executor\SeriesExecutor->run(Array, Array, Array, Object(Symfony\Component\Console\Input\ArgvInput), Object(Deployer\Console\Output\OutputWatcher))
#4 /project-root/vendor/symfony/console/Command/Command.php(255):  in /project-root/vendor/deployer/recipes/phinx.php on line 120

Fatal error: Uncaught Error: Function name must be a string in /project-root/vendor/deployer/recipes/phinx.php on line 120

Error: Function name must be a string in /project-root/vendor/deployer/recipes/phinx.php on line 120

Call Stack:
    0.0042     357872   1. {main}() php/bin/deployer.phar:0
    0.0466     708864   2. require('phar://php/bin/deployer.phar/bin/dep') php/bin/deployer.phar:4
    0.1532    4198624   3. Deployer\Deployer->run() phar://php/bin/deployer.phar/bin/dep:110
    0.1684    4333416   4. Symfony\Component\Console\Application->run() /project-root/vendor/deployer/deployer/src/Deployer.php:186
    0.1818    4334248   5. Symfony\Component\Console\Application->doRun() /project-root/vendor/symfony/console/Application.php:122
    0.1829    4334248   6. Symfony\Component\Console\Application->doRunCommand() /project-root/vendor/symfony/console/Application.php:191
    0.1830    4334248   7. Symfony\Component\Console\Command\Command->run() /project-root/vendor/symfony/console/Application.php:829
    0.1843    4336824   8. Deployer\Console\TaskCommand->execute() /project-root/vendor/symfony/console/Command/Command.php:255
    0.1879    4375224   9. Deployer\Executor\SeriesExecutor->run() /project-root/vendor/deployer/deployer/src/Console/TaskCommand.php:79
    0.1904    4409792  10. Deployer\Task\Task->run() /project-root/vendor/deployer/deployer/src/Executor/SeriesExecutor.php:40
    0.1905    4410112  11. call_user_func:{/project-root/vendor/deployer/deployer/src/Task/Task.php:91}() /project-root/vendor/deployer/deployer/src/Task/Task.php:91
    0.1906    4410112  12. Deployer\{closure}() /project-root/vendor/deployer/deployer/src/Task/Task.php:91


Variables in local scope (#12):
  $ALLOWED_OPTIONS = array (0 => 'configuration', 1 => 'date', 2 => 'environment', 3 => 'target', 4 => 'parser')
  $conf = *uninitialized*
  $phinxCmd = *uninitialized*
```

**Comment by ket4yii** [comment]
@elfet, it can be fixed by moving some functions to global scope from get/set. As I can see, you change a way to get closures from get/set(to call_user_func). Now the recipe can't pass arguments to them. How do you think, if I move functions from get/set, will it pollute global scope?

**Comment by elfet** [comment]
What functions? Why not add `namespace Deployer;`
